### ISSUE TITLE
Talk Proposal: Interactive `<cAAnvas>`

### ISSUE THREAD

**Issue by puresick** [hhtml-de/call-for-proposals#1]
### Talk title
Interactive `<cAAnvas>`

### Abstract 

One goal we are aiming for while building our new creative editor at img.ly is its WCAG 2 AA-level conformity. While reaching the conformance for most regular UI elements was a small adventure by itself, facing the `<canvas>` element (and its interactive content) felt like reaching the endboss level. 👾 

People using our editor are capable of directly interacting with different type of content which is drawn on the `<canvas>`, like e.g. manipulating images, adding vector shapes and layouting typography.
While having many advantages over drawing everything with the DOM, the big disadvantage of this approach comes with its disability to access the drawn content via assistive technolgies in a proper way.

In this talk I want to show you the problems we were (or still are) facing, how we got to working solutions and what we have learned during this process.

### Your name (and pronouns)
Daniel Henning (he/him)

### Contact Details

- Website: [hnnng.dev](http://hnnng.dev)
- eMail: contact@hnnng.dev (personal) - daniel.henning@img.ly (job-related)
- Github: [https://github.com/puresick](https://github.com/puresick)
- imd.social (Mastodon instance): [https://imd.social/@puresick](https://imd.social/@puresick)

### Code of Conduct

- [x] I've read and agree to the [HHTML Code of Conduct](https://hhtml.de/code-of-conduct/)

**Comment by learosema** [comment]
Hi @puresick, thank you for submitting your proposal. I would like to confirm your talk for the next meetup scheduled on August 31, 2021.

Best,
Lea

**Comment by puresick** [comment]
Hey @terabaud 

Sure, hereby I confirm the scheduled date from my side. :)
It is a pleasure to be able having this talk at your meetup!

Are there any other requirements I have to meet, like e.g.:
- Do you need to review my slides beforehand?
- What tool are you using for the meetup (Zoom, Jitsi, BBB, etc.)?
- Anything else?

**Comment by learosema** [comment]
@puresick thank you, super excited to see your talk. 
- I can review the slides beforehand but it is not necessary
- We will use Zoom for the meetup
- if you like, we can schedule a quick audio/video setup check, maybe one day before the meetup
- it's my first time organizing a meetup :)

**Comment by learosema** [comment]
@puresick forgot to ask: how long will your talk be? 25-30 minutes?

**Comment by puresick** [comment]
That is nice to hear, thanks! :)

A quick checkup call would be great. I am quiet flexible the day before - feel free to send me a calendar invite with a time that works for you (best would be to send it my work mail). :)

Yeah I guess the talk will be somewhat around 25 minutes.

> it's my first time organizing a meetup :)

Cool! I am sure it will be great and fun 💪
