### ISSUE TITLE
Talk proposal: React in Vue - Gracefully moving into our new apartment 🦢 ✨ 📦

### ISSUE THREAD

**Issue by h2xd** [hhtml-de/call-for-proposals#10]
### Abstract 

Image you have the duty to migrate from Vue to React while implementing new features.
Here I can give an little input on How?, WHY?, When, and wHAt? 
And maybe that is a nice conversation starter within the Meetup.

Can create some minor slides and hold in English primary and german second if wished.

Repo: https://github.com/h2xd/react-in-vue
Demo: https://h2xd.github.io/react-in-vue/

Also possible to do that tomorrow in Hamburg.

### Your name (and pronouns)
Andrej Schujkow (he/him)

### Contact Details
@h2xd

### Code of Conduct

- [x] I've read and agree to the [HHTML Code of Conduct](https://hhtml.de/code-of-conduct/)

**Comment by learosema** [comment]
Hello @h2xd, thank you for submitting the talk. I'd love to accept the talk forr for tomorrow's meetup. Would you confirm?
Best Regards, Lea

**Comment by h2xd** [comment]
For sure. Approved and accepted!

**Comment by h2xd** [comment]
Slidedeck from the Event

[HHTML-Presentation.pdf](https://github.com/hhtml-de/call-for-proposals/files/13517722/HHTML-Presentation.pdf)
