### ISSUE TITLE
Talk proposal: Creating Accessible CSS Art

### ISSUE THREAD

**Issue by alvaromontoro** [hhtml-de/call-for-proposals#2]
### Talk title

Creating Accessible CSS Art

### Abstract 

CSS art has been a thing since the creation of CSS itself. It is a great way of practicing and learning and it makes for an interesting coding challenge. But it has a big problem: CSS art is inherently not accessible. In this talk, I'll explain different HTML and CSS techniques to make your CSS art more accessible to all: from adding "alternative text", to avoiding some properties that will create trouble.

I did this as a lightning talk for a [SydCSS meetup](https://www.youtube.com/watch?v=bJRETGarbqE) (5-10 minutes), but I could extend it to 20 minutes and apply everything on an CSS art example.

### Your name (and pronouns)

Alvaro Montoro (he/him)

### Contact Details

Twitter: [@alvaro_montoro](https://twitter.com/alvaro_montoro)

### Code of Conduct

- [x] I've read and agree to the [HHTML Code of Conduct](https://hhtml.de/code-of-conduct/)

**Comment by learosema** [comment]
@alvaromontoro thank you for submitting a lightning talk. I would love to confirm it for our first meetup scheduled on August 31, 7 pm CEST
