### ISSUE TITLE
Talk Proposal: HTML: The Good Parts

### ISSUE THREAD

**Issue by pepelsbey** [hhtml-de/call-for-proposals#3]
### Talk title

HTML: The Good Parts

### Abstract

I have two descriptions. The funny one just lists all the tags:

> html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, pre, blockquote, ol, ul, menu, li, dl, dt, dd, figure, figcaption, main, div, a, em, strong, small, s, cite, q, dfn, abbr, ruby, rt, rp, data, time, code, var, samp, kbd, sub, sup, i, b, u, mark, bdi, bdo, span, br, wbr, ins, del, picture, source, img, iframe, embed, object, video, audio, track, map, area, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th, form, label, input, button, select, datalist, optgroup, option, textarea, output, progress, meter, fieldset, legend, details, summary, dialog, script, noscript, template, slot, canvas.

Together with the title it might be enough. If not, there’s a formal one:

> The best and the most valuable parts of HTML from the practical point of view: what spec to read and how to read it, streaming and rendering in browsers, elements nesting rules and possible problems, the most critical structural and content elements, new and less known attributes, tools for validation and minification, ways to extend HTML.

### Your name (and pronouns)

Vadim Makeev, he/him

### Contact Details

- [hi@pepelsbey.dev](mailto:hi@pepelsbey.dev)
- [@pepelsbey_dev](https://twitter.com/pepelsbey_dev)

### Code of Conduct

- [x] I've read and agree to the [HHTML Code of Conduct](https://hhtml.de/code-of-conduct/)

**Comment by learosema** [comment]
Hello Vadim, I would like to confirm your talk for the next meetup scheduled on November 15, 2022.

Best regards,
Lea

**Comment by pepelsbey** [comment]
@learosema thank you! I'll start preparing it. Is there are any next steps apart from joining to the call on the day?

**Comment by learosema** [comment]
If you like, we can schedule a zoom session some time before the meetup where we can talk a bit about the meetup and test the setup. Also another question is talk order, would you like to have the first talk slot in the meetup or the second one?

**Comment by pepelsbey** [comment]
Yes, let's have a call :) As for the schedule, it's up to you: I'm happy to take any slot.

**Comment by learosema** [comment]
Thank you :) I have a calendly account to schedule a meeting:
https://calendly.com/learosema/60min
