### ISSUE TITLE
Talk Proposal: The road to HTMHell is paved with semantics

### ISSUE THREAD

**Issue by pepelsbey** [hhtml-de/call-for-proposals#4]
### Talk title

The road to HTMHell is paved with semantics

### Abstract

HTML semantics is a nice idea that helped us to get through years of HTML spec crisis and markup nihilism. We got our ”new HTML5 hope” and a bunch of new semantic tags, accompanied by a few repurposed old ones. But does it really make a difference? There’s a huge gap between HTML spec’s good intentions and what browsers are willing to implement. And there’s even a bigger one between all of that and what screen readers actually support. Writing semantic markup only because [the good spec is a spec and it is good and it’s a spec](https://youtu.be/EIBRdBVkDHQ) is not the worst approach you can take, but it might lead you to HTMHell.

### Your name (and pronouns)

Vadim Makeev, he/him

### Contact Details

- [hi@pepelsbey.dev](mailto:hi@pepelsbey.dev)

### Code of Conduct

- [x] I've read and agree to the [HHTML Code of Conduct](https://hhtml.de/code-of-conduct/)

**Comment by learosema** [comment]
Hi @pepelsbey, I would like to accept the talk and look forward to seeing you on 28.09. at Factorial :)

**Comment by pepelsbey** [comment]
Yay! Looking forward to it :)

**Comment by learosema** [comment]
Thank you very much ❤️
