### ISSUE TITLE
Talk proposal: Pragmatic Responsive Images

### ISSUE THREAD

**Issue by s2b** [hhtml-de/call-for-proposals#5]
### Talk title

Pragmatic Responsive Images

### Abstract 

The topic of responsive images is full of confusion and misunderstandings. This is not a coincidence because it is a complicated subject with a lot of historical baggage. I've been searching for the perfect solution for years and instead found a pragmatic approach that has served me well in numerous web projects. And I think that I can present it in 5-10 minutes.

Background: In 2017, I created a [3rd-party-package for TYPO3 CMS](https://github.com/sitegeist/sms-responsive-images) that generates responsive image markup.

### Your name (and pronouns)

Simon Praetorius (he/him)

### Contact Details

on Mastodon: @s2b@norden.social

### Code of Conduct

- [x] I've read and agree to the [HHTML Code of Conduct](https://hhtml.de/code-of-conduct/)

**Comment by learosema** [comment]
Hello @s2b, I super much agree, had a struggle with responsive images myself a while back 😄.
We would love to hear your lightning talk and hereby accept the talk for the upcoming meetup on 28.09. 
Do you confirm?

**Comment by s2b** [comment]
Hi @learosema. Thank you for inviting me to speak at the next meetup. I confirm and I'm looking forward to it. :)

**Comment by learosema** [comment]
Thank you very much ❤️
