### ISSUE TITLE
Talk Proposal: Easy dark mode with color-scheme

### ISSUE THREAD

**Issue by sarajw** [hhtml-de/call-for-proposals#6]
### Abstract 

A mashing together of two talks - either of which alone would be a lightning talk sort of length - the length of this one may end up somewhere around 15mins:

- how to use color-scheme
- a discussion on contrast levels

I have hashed out the main points I'd cover as follows:

- default html theme (light)
- dark default also exists!
- color-scheme meta tag and CSS
- relationship to prefers-color-scheme
- system colours
- contrast of default color-schemes
- when contrast is too high
- astigmatism & halos
- migraine study
- ravelry case study
- tempering color-scheme defaults
- takeaway: give lots of options if you can!

### Your name (and pronouns)
Sara (she/her)

### Contact Details

Mastodon: @sarajw@front-end.social

### Code of Conduct

- [X] I've read and agree to the [HHTML Code of Conduct](https://hhtml.de/code-of-conduct/)

**Comment by learosema** [comment]
Hello @sarajw, I'm happy to tell you we hereby accept your talk for the upcoming meetup on September 28th 🥳 
Would you confirm?

**Comment by sarajw** [comment]
I confirm!! :) thank you

**Comment by learosema** [comment]
Thank you very much ❤️
