### ISSUE TITLE
Talk Proposal: "Eco Bytes: Crafting for a Sustainable Web"

### ISSUE THREAD

**Issue by mariohamann** [hhtml-de/call-for-proposals#7]
### Talk title
Eco Bytes: Crafting for a Sustainable Web

### Abstract

(draft)

In today's digital world, websites are getting [heavier and slower](https://almanac.httparchive.org/en/2022/page-weight#fig-7), often at the [expense of the environment](https://sustainablewebdesign.org/). In this talk I will discuss different perspectives how to serve sustainability in web development and share practical insights to create low(er)-impact websites from [own](https://leanlanding.page/) and client's projects.

### Your name (and pronouns)
Mario Hamann (he, him)

### Contact Details

mario.hamann@virtual-identity.com

### Code of Conduct

- [x] I've read and agree to the [HHTML Code of Conduct](https://hhtml.de/code-of-conduct/)

-----

PS: I'm a colleague of @pepelsbey (who encouraged me to join the round), but unfortunately not from Berlin, but from (eco city 🌱) Freiburg. If you're interested in the talk I would need to clarify my final trip to Hamburg first before being able to finally accept myself. 🙏

**Comment by learosema** [comment]
Hi @mariohamann, the talk sounds super interesting and would perfectly fit topic-wise. Unfortunately the evening is already quite packed. We already have 3 talks and one lightning talk. I'll need to sync with Factorial tomorrow and find out how long the evening may be :)

**Comment by mariohamann** [comment]
Thanks for the answer – would be happy, if it works out! 🤞

**Comment by mariohamann** [comment]
Hey @learosema, any news on it? :)

**Comment by learosema** [comment]
Hi @mariohamann, unfortutately adding another talk to the evening won't work, we're already quite full and also we have to close latest 10pm.

**Comment by mariohamann** [comment]
Totally understandable – maybe it works out next time! :) Thanks.
